name: Deploy to Render

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}  # Find this in your Render dashboard
          api_key: ${{ secrets.RENDER_API_KEY }}       # Your Render API key
          wait_deploy: true                            # Wait for deployment to complete
          github_token: ${{ secrets.GITHUB_TOKEN }}    # Automatically provided by GitHub

      - name: Deployment Status
        run: |
          echo "Deployment completed"
          echo "Check your Render dashboard for details"