name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy new Docker Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: EC2_PUBLIC_IP  # Export EC2_PUBLIC_IP as environment variable for remote commands
          script: |
            echo "Pulling latest code from GitHub..."
            cd /home/ubuntu/app
            git pull origin main

            echo "Building new Docker image..."
            docker build -t fastapi-book-app .

            echo "Stopping and removing old container (if running)..."
            docker stop fastapi-book-app-container || true # Ignore error if container doesn't exist
            docker rm fastapi-book-app-container || true   # Ignore error if container doesn't exist

            echo "Running new Docker container..."
            docker run -d --name fastapi-book-app-container -p 80:80 fastapi-book-app

            echo "Deployment complete!"
            echo "Application should be accessible at http://${{ env.EC2_PUBLIC_IP }}"